name: Generate Snake Animation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Snake Animation
      uses: Platane/snk@master
      with:
        github_user_name: tynist
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: Add GitHub contribution grid snake animation
        add: 'dist/github-contribution-grid-snake.svg'

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
